name:                server
version:             0.1.0.0
github:              "wixe/jsonserver.hs"
license:             BSD3
author:              "Vladislav Wixe"
maintainer:          "wixe@ya.ru"
copyright:           "2020 Vladislav Wixe"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/wixe/jsonserver.hs#README.md>

dependencies:
- base              >= 4.7 && < 5
- warp              == 3.3.*
- wai               == 3.2.2.*
- http-types        == 0.12.*
- text              == 1.2.*
- postgresql-simple == 0.6.*
- bytestring        == 0.10.10.*
- jwt               == 0.10.*
- time              == 1.*
- mtl               == 2.2.*
- random            == 1.*
- aeson             == 1.*
- containers        == 0.6.*
- yaml              == 0.11.*
- QuickCheck        == 2.*

ghc-options:
- -Wall
# Some exceptions:
- -Wno-name-shadowing # Very useful
- -Wno-missing-signatures # Types inferring is a feature

library:
  source-dirs: src

executables:
  server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - server

tests:
  server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - server
